### ISSUE TITLE
rounding errors in shutter time returned by database

### ISSUE THREAD

**Issue by parkus** [cmillion/gPhoton#103]
When looking into #101, I found that a shutdead query to the database gives a bad result when there is no actual exposure time.

```
ra0,dec0 = 295.019143, 39.368319
t0, t1 = t0, t1 = 899824555.35, 899825820.02
import dbasetools as dbt
import gQuery as gq

#there is FUV exposure time within this full range ra0,dec0
ft = dbt.fGetTimeRanges('FUV', [ra0, dec0], trange=[t0-1.0, t1+1.0])
ft[0,0] < t0, ft[0,1] > t1
#prints (True, True)

#but no NUV exposure time
dbt.fGetTimeRanges('NUV', [ra0, dec0], trange=[t0-1.0, t1+1.0])
#prints empty array

#running shutdead should therefore return the full time range when queried, but it does not
sd = gq.getArray(gq.shutdead('NUV', t0, t1))
sd[0][0] == (t1 - t0)
#prints False

print sd[0][0], (t1 - t0)
#prints 1264.65 1264.66999996
```

This seems to be a rounding error. If I use whole numbers for t0,t1, then t1-10 and sd[0][0] agree. Rounding errors, even at the 0.02 level, will be undesirable, especially for rapid cadences. Also, this results in the pipeline thinking there are small exposure times (sometimes negative) when there is really no exposure time. This shouldn't be an issue so long as the pipeline never accidentally tries to query a location/band with no exposure time, but if it does do so it would be nice to get the zero division error as an alert to what is up.

**Comment by cmillion** [comment]
I also found that I was just getting wrong shutter corrections from the database generally as compared to doing the calculation myself based on global time stamps. I've temporarily moved the shutter calculation onto the client side for v1.25.0. It still only requires a single query and has response time comparable to the dead time.

**Comment by bshiao** [comment]
Can you let me know query your running, etc, so I can fix this in the function.

Bernie

**Comment by cmillion** [comment]
Yes. I'm running a query that returns all DISTINCT time stamps within a given time range. Then sorting those. Then I subtract each value by the value that directly follows (excluding the end points, of course). I look for any value in the resulting array that is >= 0.05. The number of such values is the number of shutter gaps. The array manipulations on this are really fast, but the query takes >1s and returns thousands of entries; so if we can move the array manipulation into the database, the query could just return a single value.

Here is a sample query URL: http://masttest.stsci.edu/portal/Mashup/MashupQuery.asmx/GalexPhotonListQueryTest?query=select count(t) from (select time as t from GPFCore.dbo.NUVPhotonsV where time >= 901540469995 and time < 901540599995 union all select time as t from GPFCore.dbo.NUVPhotonsNULLV where time >= 901540469995 and time < 901540599995) x&format=json&timeout={}

Here's the python code (in dbasetools.py as of v1.25.0):

    def compute_shutter(band,trange,verbose=0,retries=20,shutgap=0.05):
        t = np.sort(np.array(gQuery.getArray(gQuery.uniquetimes(
            'FUV',trange[0],trange[1])),dtype='float64')[:,0]/gQuery.tscale)
        ix = np.where(t[1:]-t[:-1]>=shutgap)
        return len(ix[0])*shutgap

I also just realized that as long as I'm grabbing all of these time stamps, I don't need to independently run the dead time queries for global counts.
