### ISSUE TITLE
Treat the case where an eclipse crosses DB boundaries when querying the null tables.

### ISSUE THREAD

**Issue by scfleming** [cmillion/gPhoton#110]
"In case of searches against the null tables where the cone is bisected by a boundary I’m not sure how handles those queries.  When I load the null tables per DB I can only say whether an eclipse or a visit within an eclipse is bisected by the dec boundary so for now I’m loading the null data in these cases into both DB’s subsequently there currently the danger that these data will be represented twice when queried, possibly a “distinct” qualifier can be used in this case and then we’re ok, but I’m not sure that will work yet." -Bernie

**Comment by cmillion** [comment]
Pretty sure this is taken care of, but should test it and have a regression test in place for it.

**Comment by bshiao** [comment]
for non-null data this isn't an issue, all DB's are mutually exclusive, no single photon exists in more that one db. In the case of null data, it's all contained in one db in one table per band so the same thing applies there is no duplication of photons there either.

we should definitely have some sort of test, let's talk it over on thursday.
