### ISSUE TITLE
null data - partitioned table or one large monolithic table

### ISSUE THREAD

**Issue by bshiao** [cmillion/gPhoton#114]
null data will live in it's own database, the current thinking is to partition the tables (FUV, NUV) based on time, say 100 partitions, one tenth of the number used for non-null data.
One of the first exercises will be to compare query performance for a partitioned null table vs a single monolithic table for DB10. The monolithic table exists already in DB10, the partitioned equivalent will be built in the null data database.

**Comment by cmillion** [comment]
@bshiao What is the status of this?

**Comment by bshiao** [comment]
this can be closed, we're using a partitioned table for both FUV and NUV NULL data and those tables live in their own single database.
FUV is partitioned in monthly increments from the beginning to the end of the mission
NUV is partitioned in weekly increments from the beginning to the end of the mission
queries perform well.
