### ISSUE TITLE
Use specific defaults for photometric apertures if --suggest is used and no MCAT sources found after 2nd attempt.

### ISSUE THREAD

**Issue by scfleming** [cmillion/gPhoton#128]
Code will try 36 arcsec then 180 arcsec if --suggest is used.  If there are still no MCAT sources found, it will return a dict with None type values.  The software that calls get_mcat_data needs to be modified to check for this as a possible return result, and, if so, to just use some hard-coded values for photometric apertures.  It also needs to print a warning message (to STDOUT, to output file too maybe?) that searching for MCAT sources failed and it's using the default values for the aperture.

**Comment by cmillion** [comment]
Moved into #179.
