### ISSUE TITLE
Reduce runtime of exposure time computation.

### ISSUE THREAD

**Issue by cmillion** [cmillion/gPhoton#130]
As currently written, it makes _two_ SQL queries _per bin_. So when you start moving to smaller (and more) bins, the gAperture runtime skyrockets. Everything is done in one list comprehension in curvetools.py / quickmag() (lines 292-295), so we should be able to seamlessly sub it out for a single, dynamically created SQL query that returns the necessary shutter / deadtime values for all requested bins with just a single call.

**Comment by cmillion** [comment]
For v1.25.0, I'm consolidating the two queries required to calculate global counts into just one. This reduces the time for each deadtime calculation by ~30%.

**Comment by bshiao** [comment]
Which two queries are these?

**Comment by cmillion** [comment]
Formerly gQuery.deadtime1() and gQuery.deadtime2(). I've consolidated these with a union.

**Comment by bshiao** [comment]
Btw, you should probably use “union all” normally union will consolidate duplicates into one row which may or may not happen in this case but that’s not something you want to happen. In fact all cases of union in gPhoton should probably be changed to union all.

https://msdn.microsoft.com/en-us/library/ms180026.aspx

**Comment by cmillion** [comment]
Ok. Just did a pass on gQuery and confirmed that all occurrences of UNION are UNION ALL.

**Comment by bshiao** [comment]
Yeah, we probably covered this already eons ago now and I just forgot about it. Thanks!
I’ll double check on the DB Server side as well but that bit me in a big way early on so I think I’m using union all everywhere as well.

**Comment by cmillion** [comment]
I'm going to start a standards document in the dev/ folder with notes like this and the one about how all ranges should be [0,1).
