### ISSUE TITLE
Handle RuntimeWarning: invalid value encountered in log10

### ISSUE THREAD

**Issue by scfleming** [cmillion/gPhoton#131]
I am seeing this warning a lot from some of the white dwarf commands I've run:

gPhoton/source/galextools.py:109: RuntimeWarning: invalid value encountered in log10
  return -2.5 * np.log10(cps) + scale

Before taking the log10() here we should make sure cps is a valid number for a log10, if not, we should return the expected fail value (inf, nan, 0., something).

Here's one command that produced this error:
gAperture.py -b NUV -r 1.8873 -d 33.2916 -s 30 --addhdr --gap 1000 -a 0.00166 -i 0.00222 -o 0.00333

**Comment by cmillion** [comment]
Also could not reproduce.

python ./gAperture.py -b NUV -r 1.8873 -d 33.2916 -s 30 --addhdr --gap 1000 -a 0.00166 -i 0.00222 -o 0.00333
[]
AB Magnitudes:               
[]

**Comment by cmillion** [comment]
Note: Reproduce by changing numpy.seterr() to "warn."

**Comment by cmillion** [comment]
I was able to reproduce using the commands below.

    import numpy as np
    np.seterr(all='warn')
    import gPhoton.curvetools
    skypos = [1.8873,33.2916]
    stepsz = 30
    radius = 0.00166
    annulus = [0.00222,0.00333]
    band = 'NUV'
    maxgap = 1000
    blah = gPhoton.curvetools.getcurve(band,skypos[0],skypos[1],radius,annulus=annulus,stepsz=stepsz,maxgap=maxgap,verbose=3)

gPhoton/galextools.py:109: RuntimeWarning: invalid value encountered in log10
  return -2.5 * np.log10(cps) + scale

**Comment by cmillion** [comment]
It's occurring in galextools.counts2mag() when the background is brighter than the source, so you're getting negative cps. The `nan` value is being propagated to the output, which is what I think we want. It looks like we can probably just wrap the offending statement in `with numpy.errstate(all='ignore'):` as described here: https://stackoverflow.com/questions/10519237/python-how-to-avoid-numpy-runtimewarning-in-function-definition

This will locally (in the sense of code) override the global seterr() and suppress the warning.
