### ISSUE TITLE
gAperture uses CLOBBER, gMap uses OVERWRITE

### ISSUE THREAD

**Issue by scfleming** [cmillion/gPhoton#148]
We should be consistent, and I prefer OVERWRITE more than CLOBBER.

**Comment by bshiao** [comment]
Perhaps it can accept both. Personally I like clobber but perhaps I’m showing my age ;-), other than that I’m agnostic.

**Comment by cmillion** [comment]
Per gphot_args.py, both are valid when passed through the command line. This statement refers to when they tools are called as Python modules, though. And drilling a little deeper, both are used. I have a slight preference for using `overwrite` everywhere as the variable name within the code; it's a little more explicit. That will be a relatively minor code change. I think the command line should continue to interchangeably accept `--clobber` and `--overwrite`. Agree?

**Comment by bshiao** [comment]
Fine with me!

**Comment by scfleming** [comment]
Agreed
