### ISSUE TITLE
--maxgap and --minexp do not work as expected

### ISSUE THREAD

**Issue by cmillion** [cmillion/gPhoton#149]
Not setting these flags should be equivalent to setting them both to 1 (second). It is not. See:

`gFind --skypos '[323.06766667,0.25400000]' --total --maxgap 1 --minexp 1`
NUV: 443931.0s (raw) in 4846 exposures.
FUV: 202304.0s (raw) in 1885 exposures.

`gFind --skypos '[323.06766667,0.25400000]' --total`
NUV: 595303.0s (raw) in 381 exposures.
FUV: 259540.0s (raw) in 203 exposures.

**Comment by scfleming** [comment]
The default max. gap is 1500 sec. in gphoton_args:

parser.add_argument("-g", "--gap", "--maxgap", action="store",
        type=float, dest="maxgap", default=1500.,
        help="Maximum gap size in seconds for data to be considered "
             "contiguous.  Default = 1500.")

This is a good default (I think) when using gAperture or gMap?  But sounds like not for gFind.  Might need to have two defaults depending on whether using gFind or gAperture/gMap?

**Comment by cmillion** [comment]
Ah. I understand. It's probably fine as a default for gFind, too. We want all of the exposure time and we want exposure time from the same eclipse to (generally) be counted as part of the same observation. I'm sure we talked through this before and I just forgot.

**Comment by scfleming** [comment]
We may want to check that 1500 is actually what's needed, as opposed to 1800. or 2000., for example.

**Comment by bshiao** [comment]
You mean by “(generally)” for those eclipses that are entirely from a single observation as in anything but AIS since there can be up to I think 12 different pointings within one eclipse in the AIS  case.

**Comment by cmillion** [comment]
I was thinking more of, like, petal pattern or scan mode where the source might show up at different parts of the detector and maybe only for fractions of the eclipse. The trade-off of reduced uncertainty (due to the flat) vs. higher counting statistics (by integrating over the whole eclipse) might not be worth it in some cases, and you want to treat those as separate observations for analysis.
