### ISSUE TITLE
add an optional unique tag to sql queries for database metrics analysis

### ISSUE THREAD

**Issue by cmillion** [cmillion/gPhoton#151]

**Comment by cmillion** [comment]
important for addressing issue #150

**Comment by cmillion** [comment]
For simplicity of implementation... a comment is now appended to every SQL query with the system UNIX time (rounded to the nearest second) _at the time of module import_. So every command line call to the tools will (very likely) have a unique identifier, but things will get confusing when someone starts doing stuff from inside of the interpreter (i.e. using things as modules instead of scripts).

**Comment by bshiao** [comment]
That sounds fine to me!
