### ISSUE TITLE
must specify -i URL to pip

### ISSUE THREAD

**Issue by cmillion** [cmillion/gPhoton#153]
You can currently only install gPhoton via pip if you pass the `-i` flag to point directly at PyPI, i.e. `pip install -i https://pypi.python.org/pypi gPhoton`

This appears to be because gPhoton is not registered in the Simple Index (https://pypi.python.org/simple/), possibly because of the off-PyPI hosting hack that we had to do to get around the size limit. This is probably a question for PyPI admins.

**Comment by scfleming** [comment]
We have solved this issue and can close it?

**Comment by cmillion** [comment]
Yes.
