### ISSUE TITLE
Set default "detsize" to 1 degree everywhere.

### ISSUE THREAD

**Issue by cmillion** [cmillion/gPhoton#159]
It is currently set to 1.25 degrees (i.e. full width) in some places, which doesn't trim out (confusing and bad) edge effects. Setting it to 1 degree will conservatively trim the edges by default.

**Comment by cmillion** [comment]
So, just changing the default of detsize won't work because it is used in a lot of places to compute the detscale. I actually did a silly thing by using detsize in two distinct ways:
1. The actual physical angular diameter of the detector (in its plate scale context).
2. The angular diameter of a "virtual" detector used by various gQuery options for the purposes of edge trimming.

These should really be distinct variables with distinct names. Another option is to keep the same use of detsize everywhere but "trim" by multiplying it by some percent P. So, like, if P=.8 and detsize=1.25 then detsize_effective = 1.

**Comment by scfleming** [comment]
I would vote for making them separate variables in the code, and pushing to post-release if necessary to do it "the right way".  For initial release we can just let people be aware of edge effects in documentation...

**Comment by cmillion** [comment]
I'm not sure which method you mean as "separate variables" vs. "the right way."

**Comment by scfleming** [comment]
I prefer making them seperate variables in the code and not using a percentage to adjust inside the software, i.e., a variable for the actual detector size should be constant within the source code and the variable for the effective detector size should be a separate variable that is adjustable from the command line.

**Comment by cmillion** [comment]
Pushed this to v1.26.0 but I'm not 100% confident in it yet. Leaving this ticket open until we can test it some more.

**Comment by cmillion** [comment]
Actually set to 1.1 degrees.
