### ISSUE TITLE
gMap band keyword is case-sensitive when imported as a module

### ISSUE THREAD

**Issue by scfleming** [cmillion/gPhoton#169]
from gPhoton.gMap import gMap

gMap(band="nuv") results in an error from the argument checker, whereas it should be converted before going to argument checking.  gFind, for example, is case insensitive when importing.

**Comment by cmillion** [comment]
Huh. The lesson I'm learning is that if you want to everything to run both as a script and as a module, then you need to duplicate all of the argument checks somewhere in code.

**Comment by scfleming** [comment]
I suspect the correct answer is not to do any of the calls to the argument checking inside __main__, but to always do that at the top of the primary method that's invoked from inside __main__….it's a lesson I'm slowly learning myself as well.

**Comment by cmillion** [comment]
Yes. I think that's right.
