### ISSUE TITLE
Add global counts to lightcurve file?

### ISSUE THREAD

**Issue by cmillion** [cmillion/gPhoton#176]
Sometimes diagnostically useful, but requires an extra query per bin.

I think we probably prefer how to obtain this (via gQuery etc.) rather than add to gAperture runtime.

**Comment by scfleming** [comment]
I think last time we talked about this we decide it would be good to add to the "post-analysis" script that would make a bunch of QA plots...

**Comment by cmillion** [comment]
Ah! That's right. Do we have an issue for that? I didn't find one. Should we call it _gQA_?

**Comment by scfleming** [comment]
We should probably make it a ticket.  Most of the other "main" programs are "little-g", "one-capital", "rest lowercase", so it would be nice to try to stick to that naming convention.  Maybe "gQual" or "gPost" or something like that?

**Comment by cmillion** [comment]
Ok. Moved to issue #177.
