### ISSUE TITLE
gMap uses a LOT of memory.

### ISSUE THREAD

**Issue by cmillion** [cmillion/gPhoton#18]
There might not be a way around this...

**Comment by scfleming** [comment]
Has this been solved by the use of the memlight keyword, plus overall improvement in the speed?

**Comment by cmillion** [comment]
Yes, including the switch from using rrhr maps to direct weighting of the photons. I was able to do have a dozen very large gMap runs simultaneously on an older machine without running out of memory. I consider this to be resolved.
