### ISSUE TITLE
gFind documentatin updates

### ISSUE THREAD

**Issue by scfleming** [cmillion/gPhoton#189]
Clara found a few documentation inconsistencies with gFind, assuming she's using the latest version:

"Just to let you know, the gPhoton documentation says the default detsize is 1.25, so you might want to update that.  Also the documentation says the default maxgap is 1 second, and suggests 100 as a good maxgap to get an entire eclipse as one observation, but the gFind --help says the default is 1500."

**Comment by cmillion** [comment]
Good catches. Thanks, Clara. I'll issue these changes as a hotfix.

**Comment by cmillion** [comment]
Hotfix pushed to master.
