### ISSUE TITLE
Create a "walkthrough" example for a standard use case.

### ISSUE THREAD

**Issue by cmillion** [cmillion/gPhoton#20]
i.e. Starting with only a star of interest, investigate its properties using some combination of gPhoton and MAST Portal tools.

**Comment by cmillion** [comment]
Probably do this as an iPython notebook. Running through all the sanity checks.

**Comment by cmillion** [comment]
If ready early, can push directly to Master because it's just documentation.

**Comment by cmillion** [comment]
For now, the flare examples in the paper serve this purpose. We should do something much more thorough and soon, though.

**Comment by scfleming** [comment]
Effectively done, see iPython notebook in "examples" folder.
