### ISSUE TITLE
Handle bins with valid data inside the annulus but none inside the aperture.

### ISSUE THREAD

**Issue by cmillion** [cmillion/gPhoton#214]
Reproduce / example code as follows.

```
from gPhoton.gAperture import gAperture
import gPhoton.MCUtils as mc
import matplotlib.pyplot as plt
import numpy as np

skypos = [195.29383, 1.1277906]
radius = 19. / 3600.
annulus = [20.5 / 3600., 38. / 3600.]
stepsz = 10

pes = gAperture("FUV", skypos, radius, annulus=annulus, stepsz=stepsz)


bad = np.where(np.isnan(pes['t_mean']))

for b in bad[0]:
    t0,t1=pes['t0'][b],pes['t1'][b]
    tix = np.where((pes['photons']['t']>=t0) & (pes['photons']['t']<t1))
    ix = np.where((pes['photons']['t']>=t0) & (pes['photons']['t']<t1) &
        (mc.distance(skypos[0],skypos[1],
                     pes['photons']['ra'],pes['photons']['dec'])<=radius))
    print b, len(tix[0]), len(ix[0])

x = np.arange(len(pes['mag']))
ix = np.where(pes['flags']>0)
plt.plot(x,pes['mag'],'.')
plt.plot(x[ix],pes['mag'][ix],'x')
```

**Comment by cmillion** [comment]
So what do we actually want the behavior to be in this case? In this example, the affected bins would seem to be "significant" zeros. How do we want to encode that? This manifests in things like the magnitude and mean event position as NaN or Inf. Would we prefer something else instead? Or to drop these bins?

**Comment by scfleming** [comment]
There's two cases and I want to be clear on which one we are referring to:

1.)  The target and it's aperture fall on the detector, but there's zero events inside it.  The target and it's annulus also fall on the detector, and there were events inside it.

2.)  The target and it's aperture fall OFF of the detector, but the annulus falls on the detector and there are events inside the annulus.

I'm assuming Case 2 is already addressed by gFind / detector edge logic, and this ticket is for specifically Case 1.  In that case, I think the flux should be set to 0.  The flux error could be assigned to  a couple different options: a.)  also 0.0  b.) based on the counting error of the annulus events  c.) based on the MCAT background from the nearest source.  I'm learning towards a.) at the moment, thoughts?

**Comment by cmillion** [comment]
Case 2 is partly handled by fGetTimeRanges and will be flagged with an edge warning in any situation where that is imperfect.

`flux` and `flux_err` are already set to zero in Case 1, which is my preference. I believe the issue came up because those bins also end up with a ton of `inf` and `nan` values because, e.g., `np.log(0) == -inf` and `np.mean([]) == nan`. I have no problem with this behavior; we need something in those cells, and it should be something obviously "out of bounds." What other options do we have?

My question amounts to basically saying that I think this is a non-bug and should just be closed and maybe documented in the User Guide. (Or else I don't remember what the original concern was.)

**Comment by cmillion** [comment]
I updated the User Guide.
