### ISSUE TITLE
error in gFind regarding nearest MCAT source

### ISSUE THREAD

**Issue by scfleming** [cmillion/gPhoton#218]
<img width="1920" alt="gfinderror" src="https://cloud.githubusercontent.com/assets/1542158/16212099/911e9060-3713-11e6-8e11-aa1abefba85d.png">

**Comment by cmillion** [comment]
I'm not able to reproduce this error, and it's not obvious to me how it arose in code. I tried all of the source positions available in the posted image. Can I get the exact gFind command that produced the issue?

**Comment by cmillion** [comment]
Was able to reproduce by passing one of the positions as a string. Calling it user error!
