### ISSUE TITLE
Add warning flag is MCAT BG data is derived from median over all visits.

### ISSUE THREAD

**Issue by scfleming** [cmillion/gPhoton#223]
If the MCAT BG search results in no valid MCAT sources for a given time bin, the code default to use an average MCAT background across all visits for that bin, but this is a very rough approximation, and should be flagged for that time bin as a warning / suspicious data point (the documentation should make it clear that this warning only applies for fluxes that use the MCAT background values, annulus backgrounds are not affected).

The other option is to not add a flag, but instead add a column indicating if the MCAT background value is averaged across visits or not.  This is probably preferable, since it only impacts MCAT background corrected flux values, but it still something important to note.  Putting it as a flag bit would probably result in confusion, but putting it as a column would make it clear that this is something to be aware of sometimes.

**Comment by cmillion** [comment]
This no longer happens. If an MCAT source isn't find, then the MCAT bg is assigned a value of NULL.
