### ISSUE TITLE
Crash in error statement with MCAT return from gAperture.

### ISSUE THREAD

**Issue by scfleming** [cmillion/gPhoton#224]
Source:

from gPhoton.gAperture import gAperture

def test():
    pes = gAperture(band='NUV', skypos=[49.30437, 1.2285], radius = 0.00555556,
                    annulus = [0.005972227, 0.0103888972], stepsz = 10,
                    csvfile = 'test.csv')

if __name__ == "__main__":
    test()

Error:

Traceback (most recent call last):by.                       
  File "test.py", line 9, in <module>
    test()
  File "test.py", line 6, in test
    csvfile = 'test.csv')
  File "/Users/fleming/MY_PYTHON_PROGRAMS/gPhoton/gAperture.py", line 123, in gAperture
    minimal_output=minimal_output)
  File "/Users/fleming/MY_PYTHON_PROGRAMS/gPhoton/curvetools.py", line 1139, in write_curve
    detsize=detsize)
  File "/Users/fleming/MY_PYTHON_PROGRAMS/gPhoton/curvetools.py", line 1042, in get_curve
    stepsz=stepsz, verbose=verbose, coadd=coadd)
  File "/Users/fleming/MY_PYTHON_PROGRAMS/gPhoton/curvetools.py", line 896, in quickmag
    for tr in zip(lcurve['t0'], lcurve['t1'])])
  File "/Users/fleming/MY_PYTHON_PROGRAMS/gPhoton/dbasetools.py", line 802, in mcat_skybg
    raise 'Duplicate {b} MCAT sources at {p}?!'.format(b=band,p=skypos)
TypeError: exceptions must be old-style classes or derived from BaseException, not str

**Comment by scfleming** [comment]
Fixed the hard-crash due to exception raise, need to understand why it's being raised in first place now.

**Comment by cmillion** [comment]
Now I'm glad that I put in that check for a condition that "should never happen." The issue is that there are two apparently identical source listings in the visit-level MCAT. I don't know why that is. But I guess when this happens, it should just pick one or the other and use it rather than `raise`ing.

**Comment by scfleming** [comment]
Yeah there are multiple entries of the exact same thing looks like?  In that case just need to "unique"-ify the MCAT sources based on coordinates (and/or exact mag)?

**Comment by cmillion** [comment]
Yes to unique-ification.

**Comment by scfleming** [comment]
Fixed by removing duplicates, if number of MCAT bgs returned is > 1 and not all duplicates will still thrown an exception.  Worth exploring why there are multiple entries at the visit-level MCAT.

**Comment by bshiao** [comment]
hmm, dups in visitphotoobjall are impossible there's an enforced primary key on objid, i.e. no dups on objid. What is the query used in this particular case?
