### ISSUE TITLE
Determine how to handle leap seconds.

### ISSUE THREAD

**Issue by scfleming** [cmillion/gPhoton#227]
First, confirm that Galex Time is Unix Time - an offset, and in fact does ignore leap seconds (i.e., they didn't correct for that in the source code without documenting it).  Then determine how to handle it.  One option would be to leave Galex Time as-is, and offer a "Galex Time Leap" method, similar to the below.  Another (better?) option would be to add a few more routines to gPhoton.analysis.gtool_utils() and include JD_UTC and JD_TAI in addition to JD_TDB, since I'm pretty sure astropy handles the leap seconds natively when doing that.  

REGARDLESS of what we do, we should move the various time conversions of out the "analysis" subdirectory and put them in gphoton_utils.

------------------------

From http://docs.astropy.org/en/stable/time/

Another special case that is relatively common is a format that represents the time since a particular epoch. The classic example is Unix time which is the number of seconds since 1970-01-01 00:00:00 UTC, not counting leap seconds. What if we wanted that value but do want to count leap seconds. This would be done by using the TAI scale instead of the UTC scale. In this case we inherit from the TimeFromEpoch class and define a few class attributes:

>>>
>>> from astropy.time.formats import erfa, TimeFromEpoch
>>> class TimeUnixLeap(TimeFromEpoch):
...    """
...    Seconds from 1970-01-01 00:00:00 TAI.  Similar to Unix time
...    but this includes leap seconds.
...    """
...    name = 'unix_leap'
...    unit = 1.0 / erfa.DAYSEC  # in days (1 day == 86400 seconds)
...    epoch_val = '1970-01-01 00:00:00'
...    epoch_val2 = None
...    epoch_scale = 'tai'  # Scale for epoch_val class attribute
...    epoch_format = 'iso'  # Format for epoch_val class attribute

>>> t = Time('2000-01-01')
>>> t.unix_leap
946684832.0
>>> t.unix_leap - t.unix
32.0

**Comment by cmillion** [comment]
For now, we don't handle leap seconds. If someone needs that extra ~4 seconds of precision, they'll have to apply a correction.
