### ISSUE TITLE
bad query returns - error or server traffic?

### ISSUE THREAD

**Issue by scfleming** [cmillion/gPhoton#233]
**COMMAND:**
gAperture(band="NUV", skypos=[15.3243344217,-33.712303895],stepsz=30., csvfile="/data2/fleming/GPHOTON_OUTPU/LIGHTCURVES/sdBs/s
dB_ton_s183/sdB_ton_s183_lc.csv", maxgap=1000., overwrite=True, radius=0.003055558,annulus=[0.00356036609615,0.00566357290691], verbose
=3)

**WARNINGS:**
bad query? https://mastcomp.stsci.edu/portal/Mashup/MashupQuery.asmx/GalexPhotonListQueryTest?query=select time,ra,dec,xi,eta,x,y,flag from GPFCore.dbo.fGetNearbyObjEqNUVAllColumns(15.3243344217,-33.712303895,0.00566357290691,816822874995,816824567995,0) -- 1469468651&format=extjs                                                  
bad query? https://mastcomp.stsci.edu/portal/Mashup/MashupQuery.asmx/GalexPhotonListQueryTest?query=select time,ra,dec,xi,eta,x,y,flag from GPFCore.dbo.fGetNearbyObjEqNUVAllColumns(15.3243344217,-33.712303895,0.00566357290691,938448367995,938450045995,0) -- 1469468651&format=extjs
bad query? https://mastcomp.stsci.edu/portal/Mashup/MashupQuery.asmx/GalexPhotonListQueryTest?query=select time,ra,dec,xi,eta,x,y,flag from GPFCore.dbo.fGetNearbyObjEqNUVAllColumns(15.3243344217,-33.712303895,0.00566357290691,938548967995,938550598995,0) -- 1469468651&format=extjs

hasn't finished yet, so there might be more or not....

**Comment by cmillion** [comment]
I think it's just pulling down a ton of data on this ~16,000s field (is it also bright?) and is hiccuping. As long as it keeps chugging, everything is fine, nothing is broken...

I maybe should revise the warning so that it only shows up if something really bad happens.
