### ISSUE TITLE
hard crash in gMap due to possible bug in WCS (astropy)?

### ISSUE THREAD

**Issue by cmillion** [cmillion/gPhoton#236]
```
gPhoton.gMap(band='FUV',skypos=(342.516906738, 342.516906738),skyrange=[0.025,0.025],verbose=2,cntfile='test.fits')
```

Results in a hard crash culminating in the following:

InvalidTransformError: ERROR 7 in wcsset() at line 2101 of file cextern/wcslib/C/wcs.c:
Ill-conditioned coordinate transformation parameter.
ERROR 4 in celset() at line 422 of file cextern/wcslib/C/cel.c:
Ill-conditioned coordinate transformation parameters
No valid solution for latp for these values of phip, phi0, and theta0.

**Comment by scfleming** [comment]
You're giving gMap an invalid skypos DEC, it looks like you're giving it the same RA twice, instead of an RA and DEC.  I would have thought WCS would catch for a DEC outside -90 to 90, but still...
