### ISSUE TITLE
Cannot install gPhoton 1.27.2 from pypi

### ISSUE THREAD

**Issue by guillochon** [cmillion/gPhoton#237]
Greetings, tried installing gPhoton tonight from pypi and got the following error:

```bash
pip install -i https://pypi.python.org/pypi gPhoton
Collecting gPhoton
  Downloading https://archive.stsci.edu/prepds/gphoton/cal/gPhoton-1.27.2.tar.gz (175.4MB)
    100% |████████████████████████████████| 175.5MB 7.6kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/mw/cx3t5lyd0r785zklkf2nn9500000gn/T/pip-build-hqfw_yz2/gPhoton/setup.py", line 13, in <module>
        from gPhoton import __version__
      File "/private/var/folders/mw/cx3t5lyd0r785zklkf2nn9500000gn/T/pip-build-hqfw_yz2/gPhoton/gPhoton/__init__.py", line 8, in <module>
        from gFind import gfind as gFind
    ImportError: No module named 'gFind'
```

I also tried installing from the source with the `py3comp` branch, and got the same error. Any idea what's going on?

**Comment by scfleming** [comment]
Hmm, I haven't seen this one before.  If you're willing to try a separate approach (for testing), can you clone the github branch and try to install manually by executing 'python setup.py install' and see if it will install that way?  If you don't have root access, you can say 'python setup.py install --user' to install in a non-root area.  Also, is your version of 'pip' up-to-date?  Thanks for being patient!

**Comment by guillochon** [comment]
@scfleming I *think* this might be because I upgraded to OS X Sierra tonight, it can't find any of my packages installed via `pip`. Let me try a few things and I'll update.

**Comment by scfleming** [comment]
Ah, I haven't taken the plunge yet myself, please keep me posted.

**Comment by guillochon** [comment]
OK, I fixed some python path stuff and the issue is resolved for python2.7. However, it still persists for python3.5, and it appears it's because the setup.py file imports `__version__` from `gPhoton`, which causes its `__init__` to fire. Commenting out some lines in the `__init__.py` enabled me to install successfully:

```python
__version__ = '1.27.2'
import time
import os.path as _osp
pkg_dir = _osp.abspath(_osp.dirname(__file__))
cal_dir = _osp.join(pkg_dir, 'cal')
time_id = int(time.time()) # Define this session by time at import.
# Import the main modules here to simplify syntax to just, e.g., gPhoton.gFind
#from gFind import gfind as gFind
#from gAperture import gaperture as gAperture
#from gMap import gmap as gMap
```

**Comment by guillochon** [comment]
OK, I got it working in my branch, I had to change the `import` and `print` statements to python3 style, and convert `long` to `int`. Available here if you're interested: https://github.com/guillochon/gPhoton

I'll close this issue since I got it working.

**Comment by scfleming** [comment]
To be clear, those changes to import/print and long-to-int were needed in the py3comp branch or the master branch?  Right now, master branch = Py2.7 only and py3comp = Py2.7+Py3.5.  I didn't see any difference when I compared your py3comp to our py3comp, suggesting you changed your version of the master branch? If so, that's fine, but that never was going to work with Python3 :)

**Comment by guillochon** [comment]
You're right, I accidentally applied changes to the master, not the py3comp branch. I'll try a bit later on the py3comp branch.
