### ISSUE TITLE
add auto-download of raw6 and scst to gPipeline

### ISSUE THREAD

**Issue by cmillion** [cmillion/gPhoton#256]
Mimicking how we already deal with the calibration files. raw6 can be quite large, so it should be coded as only doing auto-download if _explicitly_ requested. But this will save a lot of headaches for anybody who wants to regenerate the photon lists.

**Comment by scfleming** [comment]
My thought was to make this part a separate module, so users can do either:
 1.)  Run gPipe by itself, assuming they aleady got the files somehow
or
2.)  Run this module, downloading 1-to-many raw files, then run gPipe separately.  Users can write their own script to combine the two how they like.

**Comment by bshiao** [comment]
So, would we want gPipeline to take 4 additional parameters, ra, dec, t0, t1 ? I can convert t0, t1 to real dates but do we want to use calendar dates in this case? Or do we not want to include t0, t1 at all and just return a complete list along with approximate start/end of each file?

I can write a stored procedure fairly quickly that would return the urls, etc, for the raw files if I know what the parameters will be based upon what is decided above.

**Comment by cmillion** [comment]
I was thinking that we'd just require eclipse number. It's the most straightforward. Doing the extra conversion from ra/dec/time to eclipse number is solving a hypothetical problem at this point. If it becomes a real problem, then we can do that.

**Comment by bshiao** [comment]
Ok, that works for me.
