### ISSUE TITLE
HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by chengchengcode** [cmillion/gPhoton#283]
I got a **HTTPError** on my laptop and received the error message like "HTTPError: HTTP Error 403: Forbidden", is this because of my internet here? or I because I haven't install some package?

Thank you very much!

Here is what did I do: I input:

```
from gPhoton import gFind
from gPhoton import gAperture
from gPhoton import gMap
import datetime

target = 'cr_dra'
ra = 244.27246917
dec = 55.26919386
step_size = 10.
img_step_size = 30.
img_size = [0.1, 0.1]
phot_rad = 0.0045
ap_in = 0.0050
ap_out = 0.0060

print("Starting gAperture for CR Draconis...")
print(datetime.datetime.now())
photon_events = gAperture(band='NUV', skypos=[ra, dec], stepsz=step_size, radius=phot_rad,
                             annulus=[ap_in, ap_out], verbose=3, csvfile=target+"_lc.csv",
                             trange=[799279196., 799280852.], overwrite=True)
print(datetime.datetime.now())
print("Completed gAperture for CR Draconis."
```

Then I got:

> Starting gAperture for CR Draconis...
> 2018-07-12 15:19:24.318369
> Using v1.28.8 of gAperture.
> Generating a light curve with the following paramters:
>  band:    NUV
>  skypos:  [244.27246917, 55.26919386]
>  tranges: [799279196.0, 799280852.0]
>  radius:  0.0045
>  annulus: [0.005, 0.006]
>  stepsz:  10.0
>  csvfile: cr_dra_lc.csv
>  verbose: 3
> Applying the response correction.                           .26919386]
> ---------------------------------------------------------------------------
> HTTPError                                 Traceback (most recent call last)
> <ipython-input-1-47854826a284> in <module>()
>      18 photon_events = gAperture(band='NUV', skypos=[ra, dec], stepsz=step_size, radius=phot_rad,
>      19                              annulus=[ap_in, ap_out], verbose=3, csvfile=target+"_lc.csv",
> ---> 20                              trange=[799279196., 799280852.], overwrite=True)
>      21 print(datetime.datetime.now())
>      22 print("Completed gAperture for CR Draconis.")
> 
> ~/anaconda3/lib/python3.6/site-packages/gPhoton/gAperture.py in gaperture(band, skypos, radius, csvfile, annulus, coadd, stepsz, verbose, overwrite, trange, tranges, minexp, maxgap, iocode, detsize, minimal_output, photoncsvfile, addhdr)
>     125                           maxgap=maxgap, iocode=iocode, detsize=detsize,
>     126                           minimal_output=minimal_output,
> --> 127                           photoncsvfile=photoncsvfile,addhdr=addhdr)
>     128 
>     129     return data
> 
> ~/anaconda3/lib/python3.6/site-packages/gPhoton/curvetools.py in write_curve(band, ra0, dec0, radius, csvfile, annulus, stepsz, trange, tranges, verbose, coadd, iocode, detsize, overwrite, minexp, maxgap, minimal_output, photoncsvfile, addhdr, commentchar)
>    1223                      trange=trange, tranges=tranges, verbose=verbose,
>    1224                      coadd=coadd, minexp=minexp, maxgap=maxgap,
> -> 1225                      detsize=detsize)
>    1226     if not data:
>    1227         if verbose:
> 
> ~/anaconda3/lib/python3.6/site-packages/gPhoton/curvetools.py in get_curve(band, ra0, dec0, radius, annulus, stepsz, trange, tranges, verbose, coadd, minexp, maxgap, detsize)
>    1118                            # for reproducibility and bin-matching
>    1119     lcurve = quickmag(band, ra0, dec0, tranges, radius, annulus=annulus,
> -> 1120                       stepsz=stepsz, verbose=verbose, coadd=coadd)
>    1121     if not lcurve:
>    1122         return None
> 
> ~/anaconda3/lib/python3.6/site-packages/gPhoton/curvetools.py in quickmag(band, ra0, dec0, tranges, radius, annulus, stepsz, verbose, detsize, coadd)
>     894     searchradius = radius if annulus is None else annulus[1]
>     895     data = pullphotons(band, ra0, dec0, tranges, searchradius, verbose=verbose,
> --> 896                        detsize=detsize)
>     897     if not data:
>     898         return None
> 
> ~/anaconda3/lib/python3.6/site-packages/gPhoton/curvetools.py in pullphotons(band, ra0, dec0, tranges, radius, verbose, flag, photonfile, detsize)
>     397 
>     398     try:
> --> 399         events = hashresponse(band, events, verbose=verbose)
>     400         return events
>     401     except TypeError:
> 
> ~/anaconda3/lib/python3.6/site-packages/gPhoton/curvetools.py in hashresponse(band, events, verbose)
>     185     if verbose:
>     186         mc.print_inline("Applying the response correction.")
> --> 187     flat, _ = cal.flat(band)
>     188 
>     189     events['col'], events['row'] = xieta2colrow(
> 
> ~/anaconda3/lib/python3.6/site-packages/gPhoton/cal/__init__.py in flat(band, buffer)
>     159 def flat(band, buffer=False):
>     160     fn = '{b}_flat.fits'.format(b=check_band(band))
> --> 161     return addbuffer(fn) if buffer else read_data(fn)
>     162 
>     163 def distortion(band, xy, eclipse, raw_stimsep):
> 
> ~/anaconda3/lib/python3.6/site-packages/gPhoton/cal/__init__.py in read_data(fn, dim)
>     106     if not _os.path.exists(path):
>     107         data_url='{b}/{f}'.format(b=cal_url,f=fn)
> --> 108         fitsdata = download_with_progress_bar(data_url, path)
>     109     if '.fits' in fn:
>     110         return get_fits_data(path, dim=dim), get_fits_header(path)
> 
> ~/anaconda3/lib/python3.6/site-packages/gPhoton/cal/__init__.py in download_with_progress_bar(data_url, file_path)
>      61         _os.makedirs(_os.path.dirname(file_path))
>      62     num_units = 40
> ---> 63     fhandle = urlopen(data_url)
>      64     content_length = url_content_length(fhandle)
>      65     chunk_size = content_length // num_units
> 
> ~/anaconda3/lib/python3.6/urllib/request.py in urlopen(url, data, timeout, cafile, capath, cadefault, context)
>     221     else:
>     222         opener = _opener
> --> 223     return opener.open(url, data, timeout)
>     224 
>     225 def install_opener(opener):
> 
> ~/anaconda3/lib/python3.6/urllib/request.py in open(self, fullurl, data, timeout)
>     530         for processor in self.process_response.get(protocol, []):
>     531             meth = getattr(processor, meth_name)
> --> 532             response = meth(req, response)
>     533 
>     534         return response
> 
> ~/anaconda3/lib/python3.6/urllib/request.py in http_response(self, request, response)
>     640         if not (200 <= code < 300):
>     641             response = self.parent.error(
> --> 642                 'http', request, response, code, msg, hdrs)
>     643 
>     644         return response
> 
> ~/anaconda3/lib/python3.6/urllib/request.py in error(self, proto, *args)
>     568         if http_err:
>     569             args = (dict, 'default', 'http_error_default') + orig_args
> --> 570             return self._call_chain(*args)
>     571 
>     572 # XXX probably also want an abstract factory that knows when it makes
> 
> ~/anaconda3/lib/python3.6/urllib/request.py in _call_chain(self, chain, kind, meth_name, *args)
>     502         for handler in handlers:
>     503             func = getattr(handler, meth_name)
> --> 504             result = func(*args)
>     505             if result is not None:
>     506                 return result
> 
> ~/anaconda3/lib/python3.6/urllib/request.py in http_error_default(self, req, fp, code, msg, hdrs)
>     648 class HTTPDefaultErrorHandler(BaseHandler):
>     649     def http_error_default(self, req, fp, code, msg, hdrs):
> --> 650         raise HTTPError(req.full_url, code, msg, hdrs, fp)
>     651 
>     652 class HTTPRedirectHandler(BaseHandler):
> 
> HTTPError: HTTP Error 403: Forbidden

**Comment by cmillion** [comment]
I think that it is probably on your end because the commands successfully executed for me.
