### ISSUE TITLE
gFind and gAperture won't run

### ISSUE THREAD

**Issue by josephguidry** [cmillion/gPhoton#285]
I've been trying to run the tutorial codes form the user guide here and from the MAST page (https://archive.stsci.edu/prepds/gphoton/index.html), but they have been completely unsuccessful. I am running these codes in jupyter using Python 2.7.15 from the anaconda distribution on a Windows 10 machine, and I've imported and called all the necessary packages and functions.

Whenever I try to execute this example gFind code from the user guide:
`gFind(band='NUV',skypos=[176.91975, 0.25561], maxgap=100, minexp=100)`

it yields this error:
"ERROR
Unsuccessful query: https://mastcomp.stsci.edu/portal/Mashup/MashupQuery.asmx/GalexPhotonListQueryTest?query=select distinct time from GPFCore.dbo.fGetNearbyAspectEq(177.975,5.4778,((1.1/2.0)*60.0),1000,1e+15) where band='NUV' or band='FUV/NUV' order by time -- 1532968520&format=extjs"

And this one: "ValueError: Incorrect syntax near '15'. Arithmetic overflow occurred."

When I run this gAperutre code from the MAST page:
`def main():
    gAperture(band='NUV', skypos=[176.91975, 0.25561], stepsz=10.,csvfile='gj_3685a_lc.csv', radius=0.012,annulus=[0.013,0.016],trange=[766525335.,766526573.])

if __name__ == '__main__':
    main()`

nothing happens at all. The code runs, but no csv file is produced, nor is any sort of light curve generated.

In the user guide it states that you "haven't actually tried to do any of this on Windows," so is it possible that the gPhoton is not compatible with Windows? Again, I am running the Python 2.7.15 anaconda distribution and have my packages updated and called each necessary function/package before running these codes.

Thanks!

**Comment by scfleming** [comment]
gPhoton is now Python 3.x only, so you'll just need to upgrade your Python version to (ideally) 3.6 and then you should be good to go.

**Comment by josephguidry** [comment]
Okay, thank you!

I recommend that you amend the User Guide so that it states it's incompatible with 2.7.x.
