### ISSUE TITLE
gMap error

### ISSUE THREAD

**Issue by Tiantian92** [cmillion/gPhoton#288]
Hi, 
I meet an error when I use gMap download the data.
The error is "TypeError: 'numpy.float64' object cannot be interpreted as an integer" by  Python 3.8.9. 
If this issue could be resolved?

**Comment by cmillion** [comment]
Image creation was always somewhat fragile and was never tested in the newest versions of Python.

I suggest that you use the newer gPhoton2 instead. https://github.com/millionconcepts/gphoton2

**Comment by Tiantian92** [comment]
Thanks for your reply！！！ I will try that.

> Image creation was always somewhat fragile and was never tested in the newest versions of Python.
> 
> I suggest that you use the newer gPhoton2 instead. https://github.com/millionconcepts/gphoton2
