### ISSUE TITLE
Non-responsiveness of gAperture

### ISSUE THREAD

**Issue by DavidMoiseNataf** [cmillion/gPhoton#289]
Hi,

I am using Mac OS-x with an Apple M1 chip and an up-to-date python 3.9 installation. I have numpy, scipy, future, etc installed on my machine, though I did verify by trying to install the dependencies listed in the user guide, and my terminal told me that I already have them. 

I'm trying to make a lightcurve. The following command is inspired by the instructions in the user guide, but it yields no result. Can you explain why?

 gAperture -b 'NUV' -r 256.5229102004 -d -26.5805651308 -a 0.1 -i 0.1 -o 0.5 -s 100 --addhdr
 
 It is centered on the star Gaia DR3 4111834567779557376, which has G=7.07 and G_BP=7.58, so it should be bright enough to be well detected in GALEX.

**Comment by scfleming** [comment]
That target doesn't have any GALEX coverage (you can confirm by running gFind on that coordinate to ask how much exposure time coverage exists in GALEX for that part of the sky).  GALEX covered ~75% of the sky, so while a lot of areas of the sky have at least some depth of coverage, it is not complete like Gaia is.

**Comment by scfleming** [comment]
I ran this command (to give a specific example)

expt = gFind(band="both", exponly=True, skypos=[coord.ra.deg, coord.dec.deg], verbose=0, detsize=1.25)

with ra, dec set to ra = 256.5229102004, dec = -26.5805651308.  I also did a search on the MAST Portal and confirmed that there is no GALEX footprint that overlaps this target on the sky.
