### ISSUE TITLE
invalid error in divide

### ISSUE THREAD

**Issue by scfleming** [cmillion/gPhoton#29]
Command:
python ./gMap.py -b 'NUV' -r 294.86493 -d 47.30736 --angle 0.2 --t0 926297927.995 --t1 995662392.995 --count /data2/fleming/GPHOTON_OUTPUT/KeplerOverlap/KIC_10281890/lc.mov.fits --frame 30 -v 1

Warning:
/home/fleming/MY_PYTHON_PROGRAMS/gPhoton/source/imagetools.py:255: RuntimeWarning: invalid value encountered in divide
  int_temp = count[i]/rr[i]

**Comment by cmillion** [comment]
We don't even apply the relative response like that anymore.
