### ISSUE TITLE
new runtime warnings appearing

### ISSUE THREAD

**Issue by scfleming** [cmillion/gPhoton#38]
python /home/fleming/MY_PYTHON_PROGRAMS/gPhoton/source/gAperture.py -b NUV -r 294.2163405 -d 46.38901 -s 60 -f /data2/fleming/GPHOTON_OUTPUT/LIGHTCURVES/GI6_079002_Kepler
_BR_Cyg/GPHOTON_OUTPUT/KEP_09655055/KEP_09655055_lc.csv --hrbg --stamp /data2/fleming/GPHOTON_OUTPUT/LIGHTCURVES/GI6_079002_Kepler_BR_Cyg/GPHOTON_OUTPUT/KEP_09655055/KEP_
09655055_stamp.jpg --addhdr --gap 1000 --suggest --overwrite

New warnings that I have not seen before are:
/usr/stsci/ssbx/python/lib/python2.7/site-packages/numpy/core/_methods.py:55: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
/usr/stsci/ssbx/python/lib/python2.7/site-packages/numpy/core/_methods.py:67: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

The first one seems like it's fine to have the warning there, I mostly want to mention it just to make sure a mean of an empty slice SHOULD actually be taking place here.  The second one sounds more like something that can be fixed in the code to avoid altogether….

**Comment by cmillion** [comment]
I can't reproduce this in the current version of the pipeline (in which --hrbg has been deprecated).
